# Generated by Django 5.0.2 on 2024-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="pdf_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="video_url",
            field=models.URLField(null=True),
        ),
    ]
