# Generated by Django 5.0.2 on 2024-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0002_alter_screen_pdf_url_alter_screen_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="pdf_url",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="video_url",
        ),
        migrations.AddField(
            model_name="screen",
            name="pdf_path",
            field=models.FilePathField(null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="video_path",
            field=models.FilePathField(null=True),
        ),
    ]
