# Generated by Django 5.1.7 on 2025-04-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0002_alter_historicalstartupchecksheet_checkpoint_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_26",
            field=models.CharField(
                blank=True,
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("available", "AVAILABLE"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                null=True,
                verbose_name="Check Point 26",
            ),
        ),
        migrations.AddField(
            model_name="startupchecksheet",
            name="checkpoint_26",
            field=models.CharField(
                blank=True,
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("available", "AVAILABLE"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                null=True,
                verbose_name="Check Point 26",
            ),
        ),
    ]
