# Generated by Django 5.1.7 on 2025-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0003_historicalstartupchecksheet_checkpoint_26_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_1",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 1",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_10",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 10",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_11",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 11",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_12",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 12",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_13",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 13",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_14",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 14",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_15",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 15",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_16",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 16",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_17",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 17",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_18",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 18",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_19",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 19",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_2",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 2",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_20",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 20",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_21",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 21",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_22",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 22",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_23",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 23",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_24",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 24",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_25",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 25",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_26",
            field=models.CharField(
                blank=True,
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                null=True,
                verbose_name="Check Point 26",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_3",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 3",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_4",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 4",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_5",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 5",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_6",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 6",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_7",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 7",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_8",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 8",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstartupchecksheet",
            name="checkpoint_9",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 9",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_1",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 1",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_10",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 10",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_11",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 11",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_12",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 12",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_13",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 13",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_14",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 14",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_15",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 15",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_16",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 16",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_17",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 17",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_18",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 18",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_19",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 19",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_2",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 2",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_20",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 20",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_21",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 21",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_22",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 22",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_23",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 23",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_24",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 24",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_25",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 25",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_26",
            field=models.CharField(
                blank=True,
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                null=True,
                verbose_name="Check Point 26",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_3",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 3",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_4",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 4",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_5",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 5",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_6",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 6",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_7",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 7",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_8",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 8",
            ),
        ),
        migrations.AlterField(
            model_name="startupchecksheet",
            name="checkpoint_9",
            field=models.CharField(
                choices=[
                    ("✔", "OK"),
                    ("✘", "Not OK"),
                    ("not applicable", "Not Applicable"),
                    ("not available", "Not AVAILABLE"),
                ],
                max_length=60,
                verbose_name="Check Point 9",
            ),
        ),
    ]
