# Generated by Django 5.1.7 on 2025-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0004_alter_historicalstartupchecksheet_checkpoint_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrejectionsheet",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rejectionsheet",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
