# Generated by Django 5.1.7 on 2025-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0005_historicalrejectionsheet_part_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalmonthlychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalweeklychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="monthlychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="weeklychecklistitem",
            name="part_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
