# Generated by Django 5.1.7 on 2025-05-15 13:25

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0006_dailychecklistitem_part_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPCBPanelInspectionRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(blank=True, default="A-SMT-07", max_length=20),
                ),
                (
                    "rev_number",
                    models.CharField(blank=True, default="00", max_length=20),
                ),
                (
                    "doc_date",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "pcb_number",
                    models.CharField(max_length=100, verbose_name="PCB No. / Rev."),
                ),
                ("customer", models.CharField(max_length=100)),
                ("pcb_batch_code", models.CharField(max_length=100)),
                (
                    "inspection_qty",
                    models.IntegerField(
                        default=5, help_text="Number of pieces inspected"
                    ),
                ),
                (
                    "no_masking_issue",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No peel off, No foreign material",
                        max_length=10,
                    ),
                ),
                (
                    "no_dust_contamination",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No Dust or contamination on PCB Panel",
                        max_length=10,
                    ),
                ),
                (
                    "no_track_damage",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No Track cut / damage mark on PCB Panel",
                        max_length=10,
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=100)),
                ("line", models.CharField(blank=True, max_length=100)),
                ("plant", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator_name",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="screen_app.processmachinemapping",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical PCB Panel Inspection Record",
                "verbose_name_plural": "historical PCB Panel Inspection Records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PCBPanelInspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(blank=True, default="A-SMT-07", max_length=20),
                ),
                (
                    "rev_number",
                    models.CharField(blank=True, default="00", max_length=20),
                ),
                (
                    "doc_date",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "pcb_number",
                    models.CharField(max_length=100, verbose_name="PCB No. / Rev."),
                ),
                ("customer", models.CharField(max_length=100)),
                ("pcb_batch_code", models.CharField(max_length=100)),
                (
                    "inspection_qty",
                    models.IntegerField(
                        default=5, help_text="Number of pieces inspected"
                    ),
                ),
                (
                    "no_masking_issue",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No peel off, No foreign material",
                        max_length=10,
                    ),
                ),
                (
                    "no_dust_contamination",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No Dust or contamination on PCB Panel",
                        max_length=10,
                    ),
                ),
                (
                    "no_track_damage",
                    models.CharField(
                        choices=[("OK", "OK"), ("Not OK", "Not OK")],
                        help_text="No Track cut / damage mark on PCB Panel",
                        max_length=10,
                    ),
                ),
                ("station", models.CharField(blank=True, max_length=100)),
                ("line", models.CharField(blank=True, max_length=100)),
                ("plant", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "operator_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcb_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PCBPanelInspectionRecords",
                        to="screen_app.processmachinemapping",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcb_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCB Panel Inspection Record",
                "verbose_name_plural": "PCB Panel Inspection Records",
            },
        ),
    ]
