# Generated by Django 5.0.2 on 2024-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0006_alter_screen_pdf_path_alter_screen_video_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="pdf_path",
            field=models.FilePathField(null=True, path="/"),
        ),
        migrations.AlterField(
            model_name="screen",
            name="video_path",
            field=models.FilePathField(null=True, path="/"),
        ),
    ]
