# Generated by Django 5.0.2 on 2024-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0007_alter_screen_pdf_path_alter_screen_video_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="pdf_path",
            field=models.FilePathField(
                null=True,
                path="/Users/anils/pydjango/django-project/sopdisplay/static/images/content/",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="video_path",
            field=models.FilePathField(
                null=True,
                path="/Users/anils/pydjango/django-project/sopdisplay/static/images/content/",
            ),
        ),
    ]
