# Generated by Django 5.1.7 on 2025-05-15 14:01

import datetime
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0007_historicalpcbpanelinspectionrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReworkAnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(blank=True, default="QSF-22-02", max_length=20),
                ),
                (
                    "rev_number",
                    models.CharField(blank=True, default="03", max_length=20),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, default=datetime.date(2023, 12, 29)),
                ),
                ("month", models.CharField(blank=True, max_length=20)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("department_name", models.CharField(blank=True, max_length=100)),
                ("process", models.CharField(blank=True, max_length=100)),
                ("sr_no", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "problem_found_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "part_received_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "line_shift",
                    models.CharField(max_length=50, verbose_name="Line/Shift"),
                ),
                (
                    "part_identification_no",
                    models.CharField(
                        max_length=100, verbose_name="Part Identification No."
                    ),
                ),
                ("short_code", models.CharField(blank=True, max_length=50)),
                ("problem_found_stage", models.CharField(max_length=100)),
                ("defects_details", models.TextField()),
                ("defect_location_on_pcb", models.CharField(max_length=100)),
                ("defect_qty", models.PositiveIntegerField(default=1)),
                ("analysis_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "child_part_im_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Child Part IM Code"
                    ),
                ),
                ("component_package_size", models.CharField(blank=True, max_length=50)),
                ("reason_for_defect", models.TextField()),
                ("rework_details", models.TextField()),
                ("rework_date", models.DateField(default=django.utils.timezone.now)),
                ("rework_done_by", models.CharField(max_length=100)),
                (
                    "part_status",
                    models.CharField(
                        choices=[("Rework", "Rework"), ("Scrap", "Scrap")],
                        default="Rework",
                        max_length=10,
                    ),
                ),
                (
                    "part_re_verification",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Fail", "Fail")],
                        default="Pass",
                        max_length=5,
                        verbose_name="Part Re-verification Status",
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Verified by (Line Supervisor)",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="screen_app.processmachinemapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rework Analysis Record",
                "verbose_name_plural": "historical Rework Analysis Records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReworkAnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(blank=True, default="QSF-22-02", max_length=20),
                ),
                (
                    "rev_number",
                    models.CharField(blank=True, default="03", max_length=20),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, default=datetime.date(2023, 12, 29)),
                ),
                ("month", models.CharField(blank=True, max_length=20)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("department_name", models.CharField(blank=True, max_length=100)),
                ("process", models.CharField(blank=True, max_length=100)),
                ("sr_no", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "problem_found_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "part_received_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "line_shift",
                    models.CharField(max_length=50, verbose_name="Line/Shift"),
                ),
                (
                    "part_identification_no",
                    models.CharField(
                        max_length=100, verbose_name="Part Identification No."
                    ),
                ),
                ("short_code", models.CharField(blank=True, max_length=50)),
                ("problem_found_stage", models.CharField(max_length=100)),
                ("defects_details", models.TextField()),
                ("defect_location_on_pcb", models.CharField(max_length=100)),
                ("defect_qty", models.PositiveIntegerField(default=1)),
                ("analysis_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "child_part_im_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Child Part IM Code"
                    ),
                ),
                ("component_package_size", models.CharField(blank=True, max_length=50)),
                ("reason_for_defect", models.TextField()),
                ("rework_details", models.TextField()),
                ("rework_date", models.DateField(default=django.utils.timezone.now)),
                ("rework_done_by", models.CharField(max_length=100)),
                (
                    "part_status",
                    models.CharField(
                        choices=[("Rework", "Rework"), ("Scrap", "Scrap")],
                        default="Rework",
                        max_length=10,
                    ),
                ),
                (
                    "part_re_verification",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Fail", "Fail")],
                        default="Pass",
                        max_length=5,
                        verbose_name="Part Re-verification Status",
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Verified by (Line Supervisor)",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rework_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_analyses",
                        to="screen_app.processmachinemapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rework Analysis Record",
                "verbose_name_plural": "Rework Analysis Records",
                "ordering": ["-problem_found_date", "sr_no"],
            },
        ),
    ]
