# Generated by Django 5.1.7 on 2025-05-15 14:30

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0008_historicalreworkanalysisrecord_reworkanalysisrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSolderPasteControl",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "paste_type",
                    models.CharField(default="Lead Free Solder Paste", max_length=50),
                ),
                ("paste_make", models.CharField(default="Heraeus", max_length=50)),
                (
                    "part_number",
                    models.CharField(default="F640SA30C5-89M30", max_length=50),
                ),
                (
                    "alloy",
                    models.CharField(default="Sn 96.5; Ag 3; Cu 0.5", max_length=100),
                ),
                (
                    "mesh_type",
                    models.CharField(
                        default="Type 3 =25 -45 microns (325/=500mesh)", max_length=100
                    ),
                ),
                ("net_weight", models.CharField(default="500 Gms", max_length=20)),
                ("paste_code", models.CharField(default="G1", max_length=10)),
                (
                    "serial_number",
                    models.CharField(max_length=20, verbose_name="S No G1-"),
                ),
                (
                    "psr_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="PSR Date"
                    ),
                ),
                ("psr_number", models.CharField(max_length=20, verbose_name="PSR No.")),
                (
                    "make_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Make Status",
                    ),
                ),
                (
                    "part_number_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Part Number Status",
                    ),
                ),
                (
                    "alloy_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Alloy Status",
                    ),
                ),
                (
                    "net_weight_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Net Weight Status",
                    ),
                ),
                ("lot_number", models.CharField(max_length=50, verbose_name="Lot No")),
                ("expiry_date", models.DateField()),
                (
                    "deep_storage_jar_number",
                    models.CharField(
                        max_length=50, verbose_name="Deep Storage Tubular Jar No."
                    ),
                ),
                (
                    "thawing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Thawing Date"
                    ),
                ),
                (
                    "thawing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Thawing Time"
                    ),
                ),
                (
                    "expiry_status",
                    models.CharField(
                        choices=[("Valid", "Valid"), ("Expired", "Expired")],
                        default="Valid",
                        max_length=10,
                    ),
                ),
                (
                    "thawing_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Thawing Sign"
                    ),
                ),
                (
                    "mixing_date",
                    models.DateField(blank=True, null=True, verbose_name="Mixing Date"),
                ),
                (
                    "mixing_time",
                    models.TimeField(blank=True, null=True, verbose_name="Mixing Time"),
                ),
                (
                    "first_use_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="First Use Date"
                    ),
                ),
                (
                    "first_use_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="First Use Time"
                    ),
                ),
                (
                    "first_use_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="First Use Sign"
                    ),
                ),
                (
                    "second_use_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Second Use Date"
                    ),
                ),
                (
                    "second_use_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Second Use Time"
                    ),
                ),
                (
                    "second_use_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Second Use Sign"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="screen_app.processmachinemapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Solder Paste Control",
                "verbose_name_plural": "historical Solder Paste Controls",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SolderPasteControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paste_type",
                    models.CharField(default="Lead Free Solder Paste", max_length=50),
                ),
                ("paste_make", models.CharField(default="Heraeus", max_length=50)),
                (
                    "part_number",
                    models.CharField(default="F640SA30C5-89M30", max_length=50),
                ),
                (
                    "alloy",
                    models.CharField(default="Sn 96.5; Ag 3; Cu 0.5", max_length=100),
                ),
                (
                    "mesh_type",
                    models.CharField(
                        default="Type 3 =25 -45 microns (325/=500mesh)", max_length=100
                    ),
                ),
                ("net_weight", models.CharField(default="500 Gms", max_length=20)),
                ("paste_code", models.CharField(default="G1", max_length=10)),
                (
                    "serial_number",
                    models.CharField(max_length=20, verbose_name="S No G1-"),
                ),
                (
                    "psr_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="PSR Date"
                    ),
                ),
                ("psr_number", models.CharField(max_length=20, verbose_name="PSR No.")),
                (
                    "make_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Make Status",
                    ),
                ),
                (
                    "part_number_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Part Number Status",
                    ),
                ),
                (
                    "alloy_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Alloy Status",
                    ),
                ),
                (
                    "net_weight_status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")],
                        default="OK",
                        max_length=5,
                        verbose_name="Net Weight Status",
                    ),
                ),
                ("lot_number", models.CharField(max_length=50, verbose_name="Lot No")),
                ("expiry_date", models.DateField()),
                (
                    "deep_storage_jar_number",
                    models.CharField(
                        max_length=50, verbose_name="Deep Storage Tubular Jar No."
                    ),
                ),
                (
                    "thawing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Thawing Date"
                    ),
                ),
                (
                    "thawing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Thawing Time"
                    ),
                ),
                (
                    "expiry_status",
                    models.CharField(
                        choices=[("Valid", "Valid"), ("Expired", "Expired")],
                        default="Valid",
                        max_length=10,
                    ),
                ),
                (
                    "thawing_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Thawing Sign"
                    ),
                ),
                (
                    "mixing_date",
                    models.DateField(blank=True, null=True, verbose_name="Mixing Date"),
                ),
                (
                    "mixing_time",
                    models.TimeField(blank=True, null=True, verbose_name="Mixing Time"),
                ),
                (
                    "first_use_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="First Use Date"
                    ),
                ),
                (
                    "first_use_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="First Use Time"
                    ),
                ),
                (
                    "first_use_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="First Use Sign"
                    ),
                ),
                (
                    "second_use_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Second Use Date"
                    ),
                ),
                (
                    "second_use_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Second Use Time"
                    ),
                ),
                (
                    "second_use_sign",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Second Use Sign"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solder_paste_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solder_paste_controls",
                        to="screen_app.processmachinemapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solder Paste Control",
                "verbose_name_plural": "Solder Paste Controls",
                "ordering": ["-psr_date", "serial_number"],
            },
        ),
    ]
