# Generated by Django 5.1.7 on 2025-05-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0010_historicaltipvoltageresistancerecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltipvoltageresistancerecord",
            name="qsf_document",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default="QSF-12-09",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="screen_app.qsf",
            ),
        ),
        migrations.AlterField(
            model_name="tipvoltageresistancerecord",
            name="qsf_document",
            field=models.ForeignKey(
                blank=True,
                default="QSF-12-09",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TipVoltageResistanceRecords",
                to="screen_app.qsf",
            ),
        ),
    ]
