# Generated by Django 5.0.2 on 2024-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0010_alter_screen_pdf_path_alter_screen_video_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="video_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
