# Generated by Django 5.1.7 on 2025-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0011_alter_historicaltipvoltageresistancerecord_qsf_document_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltipvoltageresistancerecord",
            name="qsf_document",
            field=models.CharField(
                blank=True, default="QSF-12-09", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tipvoltageresistancerecord",
            name="qsf_document",
            field=models.CharField(
                blank=True, default="QSF-12-09", max_length=50, null=True
            ),
        ),
    ]
