# Generated by Django 5.0.2 on 2024-02-17 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screen_app", "0012_screen_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="station",
        ),
        migrations.DeleteModel(
            name="Station",
        ),
    ]
