# Generated by Django 5.1.7 on 2025-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0012_alter_historicaltipvoltageresistancerecord_qsf_document_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreworkanalysisrecord",
            name="defects_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreworkanalysisrecord",
            name="reason_for_defect",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreworkanalysisrecord",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreworkanalysisrecord",
            name="rework_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reworkanalysisrecord",
            name="defects_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reworkanalysisrecord",
            name="reason_for_defect",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reworkanalysisrecord",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reworkanalysisrecord",
            name="rework_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
