# Generated by Django 5.0.6 on 2024-07-22 06:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0013_remove_screen_station_delete_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixtureCleaningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_number", models.CharField(default="QSF-12-15", max_length=20)),
                ("month_year", models.DateField()),
                (
                    "shift",
                    models.CharField(choices=[("A", "A"), ("B", "B")], max_length=1),
                ),
                (
                    "fixture_location",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=10,
                    ),
                ),
                (
                    "fixture_control_no",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=2,
                    ),
                ),
                ("fixture_installation_date", models.DateField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("operator_name", models.CharField(max_length=100)),
                (
                    "verification_tag_available",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "verification_tag_condition",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "no_dust_on_fixture",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "no_epoxy_coating_on_fixture",
                    models.CharField(
                        choices=[("OK", "OK"), ("NG", "NG")], max_length=2
                    ),
                ),
                (
                    "operator_signature",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "supervisor_signature",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixture Cleaning Record",
                "verbose_name_plural": "Fixture Cleaning Records",
            },
        ),
        migrations.CreateModel(
            name="SolderingBitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        default="Doc-QSF-12-15", max_length=50, verbose_name="Doc. No."
                    ),
                ),
                (
                    "part_name",
                    models.CharField(
                        choices=[
                            ("Part 1", "Part 1 Description"),
                            ("Part 2", "Part 2 Description"),
                            ("Part 3", "Part 3 Description"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "machine_no",
                    models.CharField(
                        choices=[
                            ("M1", "Machine 1"),
                            ("M2", "Machine 2"),
                            ("M3", "Machine 3"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "machine_location",
                    models.CharField(
                        choices=[
                            ("Location A", "Location A"),
                            ("Location B", "Location B"),
                            ("Location C", "Location C"),
                        ],
                        max_length=150,
                    ),
                ),
                ("month", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("soldering_points_per_part", models.IntegerField(default=10)),
                ("bit_size", models.CharField(default="20DV", max_length=20)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "produce_quantity_shift_a",
                    models.IntegerField(verbose_name="Produce Quantity Shift A"),
                ),
                (
                    "produce_quantity_shift_b",
                    models.IntegerField(verbose_name="Produce Quantity Shift B"),
                ),
                (
                    "total_quantity",
                    models.IntegerField(
                        default=500,
                        help_text="This field is automatically calculated based on the sum of produce_quantity_shift_a and produce_quantity_shift_b.",
                        verbose_name="Total Quantity (Both shift)",
                    ),
                ),
                (
                    "total_soldering_points",
                    models.IntegerField(
                        default=500,
                        help_text="This field is automatically calculated based on the total quantity and soldering points per part.",
                        verbose_name="Total Soldering points/day",
                    ),
                ),
                (
                    "bit_life_remaining",
                    models.IntegerField(
                        default=500,
                        help_text="This field is automatically calculated based on the total quantity and the initial bit life.",
                        verbose_name="Bit Life Remaining (Parts in Nos.)",
                    ),
                ),
                ("bit_change_date", models.DateField(verbose_name="Bit Change Date")),
                (
                    "prepared_by",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Robotic Soldering Bit Replacement Record",
                "verbose_name_plural": "Robotic Soldering Bit Replacement Records",
            },
        ),
        migrations.CreateModel(
            name="RejectionSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "stage",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=7
                    ),
                ),
                (
                    "part_description",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=15
                    ),
                ),
                (
                    "opening_balance",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "receive_from_rework",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "total_pass_qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "total_rejection_qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "closing_balance",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "operator_signature",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejection Sheet",
                "verbose_name_plural": "Rejection Sheets",
                "unique_together": {("month", "stage", "part_description")},
            },
        ),
    ]
