# Generated by Django 5.0.6 on 2024-07-22 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0014_fixturecleaningrecord_solderingbitrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_number", models.CharField(default="QSF-13-06", max_length=20)),
                ("rev_number", models.CharField(default="02", max_length=10)),
                ("rev_date", models.DateField(default="2022-12-31")),
                (
                    "machine_name",
                    models.CharField(
                        choices=[
                            ("Machine 1", "Machine 1"),
                            ("Machine 2", "Machine 2"),
                            ("Machine 3", "Machine 3"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "control_number",
                    models.CharField(
                        choices=[
                            ("Control A", "Control A"),
                            ("Control B", "Control B"),
                            ("Control C", "Control C"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "machine_location",
                    models.CharField(
                        choices=[
                            ("Location A", "Location A"),
                            ("Location B", "Location B"),
                            ("Location C", "Location C"),
                        ],
                        max_length=100,
                    ),
                ),
                ("month_year", models.DateField(default=django.utils.timezone.now)),
                (
                    "check_point_1",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Clean Machine Surface",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_2",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check ON/OFF Switch",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_3",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check Emergency Switch",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_4",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check any Abnormal Sound in M/C",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_5",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check Spray Nozzle",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_6",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check all Tubbing & Feeder pipe",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_7",
                    models.CharField(
                        choices=[
                            ("Clean Machine Surface", "Clean Machine Surface"),
                            ("Check ON/OFF Switch", "Check ON/OFF Switch"),
                            ("Check Emergency Switch", "Check Emergency Switch"),
                            (
                                "Check any Abnormal Sound in M/C",
                                "Check any Abnormal Sound in M/C",
                            ),
                            ("Check Spray Nozzle", "Check Spray Nozzle"),
                            (
                                "Check all Tubbing & Feeder pipe",
                                "Check all Tubbing & Feeder pipe",
                            ),
                            (
                                "Check Maintenance & Calibration Tag",
                                "Check Maintenance & Calibration Tag",
                            ),
                        ],
                        default="Check Maintenance & Calibration Tag",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_1",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="Proper Clean",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_2",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="Proper Working",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_3",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="Proper Working",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_4",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="No any Abnormal Sound",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_5",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="No Blockage No leakage",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_6",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="No Cut & No Damage",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_7",
                    models.CharField(
                        choices=[
                            ("Proper Clean", "Proper Clean"),
                            ("Proper Working", "Proper Working"),
                            ("Proper Working", "Proper Working"),
                            ("No any Abnormal Sound", "No any Abnormal Sound"),
                            ("No Blockage No leakage", "No Blockage No leakage"),
                            ("No Cut & No Damage", "No Cut & No Damage"),
                            ("No Expiry date on tag", "No Expiry date on tag"),
                        ],
                        default="No Expiry date on tag",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_1",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="Clean by Cloths & Brush",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_2",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_3",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_4",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_5",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_6",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_7",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "Remark_1",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_2",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_3",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_4",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_5",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_6",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_7",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "checked_by_Operator",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "approved_by_Supervisor",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Checklist For Daily ",
                "verbose_name_plural": "Maintenance Checklists For Daily",
            },
        ),
        migrations.CreateModel(
            name="MonthlyChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_number", models.CharField(default="QSF-13-06", max_length=20)),
                ("rev_number", models.CharField(default="02", max_length=10)),
                ("rev_date", models.DateField(default="2022-12-31")),
                (
                    "machine_name",
                    models.CharField(
                        choices=[
                            ("Machine 1", "Machine 1"),
                            ("Machine 2", "Machine 2"),
                            ("Machine 3", "Machine 3"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "control_number",
                    models.CharField(
                        choices=[
                            ("Control A", "Control A"),
                            ("Control B", "Control B"),
                            ("Control C", "Control C"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "machine_location",
                    models.CharField(
                        choices=[
                            ("Location A", "Location A"),
                            ("Location B", "Location B"),
                            ("Location C", "Location C"),
                        ],
                        max_length=100,
                    ),
                ),
                ("month_year", models.DateField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "check_point_12",
                    models.CharField(
                        choices=[
                            (
                                "Check Machine Earthing (Leakage Voltage)",
                                "Check Machine Earthing (Leakage Voltage)",
                            ),
                            ("Check all parameter", "Check all parameter"),
                            ("Check Working condition", "Check Working condition"),
                            (
                                "Check Operation of Sensors",
                                "Check Operation of Sensors",
                            ),
                            (
                                "Check condition of all fixture",
                                "Check condition of all fixture",
                            ),
                        ],
                        default="Check Machine Earthing (Leakage Voltage)",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_12",
                    models.CharField(
                        choices=[
                            ("< 2 V", "< 2 V"),
                            ("Condition Proper", "Condition Proper"),
                            ("Condition Proper", "Condition Proper"),
                            ("Proper Condition", "Proper Condition"),
                        ],
                        default="< 2 V",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_12",
                    models.CharField(
                        choices=[
                            ("By Parameter", "By Parameter"),
                            ("By Condition", "By Condition"),
                            ("By Condition", "By Condition"),
                            ("By Fixture", "By Fixture"),
                        ],
                        default="By Parameter",
                        max_length=200,
                    ),
                ),
                (
                    "Remark_12",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_number", models.CharField(default="QSF-13-06", max_length=20)),
                ("rev_number", models.CharField(default="02", max_length=10)),
                ("rev_date", models.DateField(default="2022-12-31")),
                (
                    "machine_name",
                    models.CharField(
                        choices=[
                            ("Machine 1", "Machine 1"),
                            ("Machine 2", "Machine 2"),
                            ("Machine 3", "Machine 3"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "control_number",
                    models.CharField(
                        choices=[
                            ("Control A", "Control A"),
                            ("Control B", "Control B"),
                            ("Control C", "Control C"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "machine_location",
                    models.CharField(
                        choices=[
                            ("Location A", "Location A"),
                            ("Location B", "Location B"),
                            ("Location C", "Location C"),
                        ],
                        max_length=100,
                    ),
                ),
                ("month_year", models.DateField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "check_point_8",
                    models.CharField(
                        choices=[
                            ("Check Conveyor Belts", "Check Conveyor Belts"),
                            (
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                            ),
                            ("Check Wire & Cable", "Check Wire & Cable"),
                            ("Electrical Insulation", "Electrical Insulation"),
                        ],
                        default="Check Conveyor Belts",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_9",
                    models.CharField(
                        choices=[
                            ("Check Conveyor Belts", "Check Conveyor Belts"),
                            (
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                            ),
                            ("Check Wire & Cable", "Check Wire & Cable"),
                            ("Electrical Insulation", "Electrical Insulation"),
                        ],
                        default="Check Solder bit Assembly. For any Bolts & Screw Loose",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_10",
                    models.CharField(
                        choices=[
                            ("Check Conveyor Belts", "Check Conveyor Belts"),
                            (
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                            ),
                            ("Check Wire & Cable", "Check Wire & Cable"),
                            ("Electrical Insulation", "Electrical Insulation"),
                        ],
                        default="Check Wire & Cable",
                        max_length=200,
                    ),
                ),
                (
                    "check_point_11",
                    models.CharField(
                        choices=[
                            ("Check Conveyor Belts", "Check Conveyor Belts"),
                            (
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                                "Check Solder bit Assembly. For any Bolts & Screw Loose",
                            ),
                            ("Check Wire & Cable", "Check Wire & Cable"),
                            ("Electrical Insulation", "Electrical Insulation"),
                        ],
                        default="Electrical Insulation",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_8",
                    models.CharField(
                        choices=[
                            ("No Damage", "No Damage"),
                            ("Proper Tight", "Proper Tight"),
                            ("No Damage No Broken", "No Damage No Broken"),
                            ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                        ],
                        default="No Damage",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_9",
                    models.CharField(
                        choices=[
                            ("No Damage", "No Damage"),
                            ("Proper Tight", "Proper Tight"),
                            ("No Damage No Broken", "No Damage No Broken"),
                            ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                        ],
                        default="Proper Tight",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_10",
                    models.CharField(
                        choices=[
                            ("No Damage", "No Damage"),
                            ("Proper Tight", "Proper Tight"),
                            ("No Damage No Broken", "No Damage No Broken"),
                            ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                        ],
                        default="No Damage No Broken",
                        max_length=200,
                    ),
                ),
                (
                    "requirement_range_11",
                    models.CharField(
                        choices=[
                            ("No Damage", "No Damage"),
                            ("Proper Tight", "Proper Tight"),
                            ("No Damage No Broken", "No Damage No Broken"),
                            ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                        ],
                        default="No Cut & No Damage Wire",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_8",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="By Hand",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_9",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="By Hand",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_10",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="By Hand",
                        max_length=200,
                    ),
                ),
                (
                    "method_of_checking_11",
                    models.CharField(
                        choices=[
                            ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                            ("By Hand", "By Hand"),
                            ("By Eye", "By Eye"),
                        ],
                        default="By Hand",
                        max_length=200,
                    ),
                ),
                (
                    "Remark_8",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_9",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_10",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "Remark_11",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "checked_by_Operator",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "approved_by_Supervisor",
                    models.CharField(
                        choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                        max_length=100,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Checklist for Weekly Basis",
                "verbose_name_plural": "Maintenance Checklists for Weekly Basis",
            },
        ),
    ]
