# Generated by Django 5.0.6 on 2024-07-22 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0016_monthlychecklistitem_approved_by_supervisor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="month_year",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
