# Generated by Django 5.0.6 on 2024-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0017_alter_monthlychecklistitem_month_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="approved_by_Supervisor",
            field=models.CharField(
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="",
                max_length=100,
            ),
        ),
    ]
