# Generated by Django 5.0.6 on 2024-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0023_alter_weeklychecklistitem_approved_by_supervisor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="approved_by_Supervisor",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✘",
                max_length=100,
            ),
        ),
    ]
