# Generated by Django 5.0.6 on 2024-07-22 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0024_alter_weeklychecklistitem_approved_by_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="approved_by_Supervisor",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
