# Generated by Django 5.0.6 on 2024-07-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0025_alter_monthlychecklistitem_approved_by_supervisor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecklistitem",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 22, 10, 21, 21, 214359, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
