# Generated by Django 5.0.6 on 2024-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0030_alter_dailychecklistitem_checked_by_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="checked_by_Operator",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✔",
                max_length=100,
            ),
        ),
    ]
