# Generated by Django 5.0.6 on 2024-08-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0033_alter_dailychecklistitem_method_of_checking_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="Clean by Cloths & Brush",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Eye",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_5",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Eye",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_6",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Eye",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="method_of_checking_7",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Eye",
                max_length=200,
            ),
        ),
    ]
