# Generated by Django 5.0.6 on 2024-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0034_alter_dailychecklistitem_method_of_checking_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="station",
            field=models.CharField(
                choices=[
                    ("TSC 01", "TSC 01"),
                    ("TSC 02", "TSC 02"),
                    ("TSC 04", "TSC 04"),
                    ("TSC 05", "TSC 05"),
                    ("TSC 09", "TSC 09"),
                    ("EBE 01", "EBE 01"),
                    ("CSL 01", "CSL 01"),
                    ("DTR 03", "DTR 03"),
                    ("DTR 05", "DTR 05"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
