# Generated by Django 5.0.6 on 2024-08-15 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0037_alter_dailychecklistitem_rev_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="check_point_10",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Check Conveyor Belts", "Check Conveyor Belts"),
                    (
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                    ),
                    ("Check Wire & Cable", "Check Wire & Cable"),
                    ("Electrical Insulation", "Electrical Insulation"),
                ],
                default="Check Wire & Cable",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="check_point_11",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Check Conveyor Belts", "Check Conveyor Belts"),
                    (
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                    ),
                    ("Check Wire & Cable", "Check Wire & Cable"),
                    ("Electrical Insulation", "Electrical Insulation"),
                ],
                default="Electrical Insulation",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="check_point_8",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Check Conveyor Belts", "Check Conveyor Belts"),
                    (
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                    ),
                    ("Check Wire & Cable", "Check Wire & Cable"),
                    ("Electrical Insulation", "Electrical Insulation"),
                ],
                default="Check Conveyor Belts",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="check_point_9",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Check Conveyor Belts", "Check Conveyor Belts"),
                    (
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                        "Check Solder bit Assembly. For any Bolts & Screw Loose",
                    ),
                    ("Check Wire & Cable", "Check Wire & Cable"),
                    ("Electrical Insulation", "Electrical Insulation"),
                ],
                default="Check Solder bit Assembly. For any Bolts & Screw Loose",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="doc_number",
            field=models.CharField(blank=True, default="QSF-13-06", max_length=20),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="method_of_checking_10",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="method_of_checking_11",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="method_of_checking_8",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="method_of_checking_9",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clean by Cloths & Brush", "Clean by Cloths & Brush"),
                    ("By Hand", "By Hand"),
                    ("By Eye", "By Eye"),
                ],
                default="By Hand",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="month_year",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="requirement_range_10",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Damage", "No Damage"),
                    ("Proper Tight", "Proper Tight"),
                    ("No Damage No Broken", "No Damage No Broken"),
                    ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                ],
                default="No Damage No Broken",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="requirement_range_11",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Damage", "No Damage"),
                    ("Proper Tight", "Proper Tight"),
                    ("No Damage No Broken", "No Damage No Broken"),
                    ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                ],
                default="No Cut & No Damage Wire",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="requirement_range_8",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Damage", "No Damage"),
                    ("Proper Tight", "Proper Tight"),
                    ("No Damage No Broken", "No Damage No Broken"),
                    ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                ],
                default="No Damage",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="requirement_range_9",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Damage", "No Damage"),
                    ("Proper Tight", "Proper Tight"),
                    ("No Damage No Broken", "No Damage No Broken"),
                    ("No Cut & No Damage Wire", "No Cut & No Damage Wire"),
                ],
                default="Proper Tight",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="rev_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="station",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
