# Generated by Django 5.0.6 on 2024-08-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0038_alter_weeklychecklistitem_check_point_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="checked_by_Operator",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✔",
                max_length=100,
            ),
        ),
    ]
