# Generated by Django 5.0.6 on 2024-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0041_alter_dailychecklistitem_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlChartReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reading1", models.FloatField()),
                ("reading2", models.FloatField()),
                ("reading3", models.FloatField()),
                ("reading4", models.FloatField()),
                ("reading5", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ControlChartStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("x_bar", models.FloatField()),
                ("r", models.FloatField()),
            ],
        ),
    ]
