# Generated by Django 5.0.6 on 2024-08-15 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0043_alter_dailychecklistitem_station_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="fixture_control_no",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
