# Generated by Django 5.0.6 on 2024-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0045_alter_fixturecleaningrecord_operator_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="doc_number",
            field=models.CharField(blank=True, default="QSF-12-15", max_length=20),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="station",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                default="DSL01_S01",
                max_length=100,
            ),
        ),
    ]
