# Generated by Django 5.0.6 on 2024-08-15 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0049_alter_fixturecleaningrecord_operator_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rejectionsheet",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="month",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="operator_signature",
            field=models.CharField(
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✔",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="station",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                default="DSL01_S01",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="verified_by",
            field=models.CharField(
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✘",
                max_length=1,
            ),
        ),
    ]
