# Generated by Django 5.0.6 on 2024-08-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0050_alter_rejectionsheet_date_alter_rejectionsheet_month_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionsheet",
            name="operator_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="operator_signature",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✔",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="verified_by",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="✘",
                max_length=1,
            ),
        ),
    ]
