# Generated by Django 5.0.6 on 2024-08-15 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0051_rejectionsheet_operator_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solderingbitrecord",
            name="operator_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="doc_number",
            field=models.CharField(
                blank=True,
                default="Doc-QSF-12-15",
                max_length=50,
                verbose_name="Doc. No.",
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="month",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="station",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                default="DSL01_S01",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
