# Generated by Django 5.0.6 on 2024-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0053_alter_solderingbitrecord_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="bit_life_remaining",
            field=models.IntegerField(
                blank=True,
                default=500,
                help_text="This field is automatically calculated based on the total quantity and the initial bit life.",
                verbose_name="Bit Life Remaining (Parts in Nos.)",
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="total_soldering_points",
            field=models.IntegerField(
                blank=True,
                default=500,
                help_text="This field is automatically calculated based on the total quantity and soldering points per part.",
                verbose_name="Total Soldering points/day",
            ),
        ),
    ]
