# Generated by Django 5.0.6 on 2024-08-15 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0054_alter_solderingbitrecord_bit_life_remaining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
