# Generated by Django 5.0.6 on 2024-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0055_alter_solderingbitrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="fixture_control_no",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="machine_location",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                max_length=150,
            ),
        ),
    ]
