# Generated by Django 5.1 on 2024-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0056_alter_fixturecleaningrecord_fixture_control_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="bit_life_remaining",
            field=models.IntegerField(
                default=500, verbose_name="Bit Life Remaining (Parts in Nos.)"
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="machine_location",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="station",
            field=models.CharField(default="DSL01_S01", max_length=100),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="total_quantity",
            field=models.IntegerField(
                default=500, verbose_name="Total Quantity (Both shifts)"
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="total_soldering_points",
            field=models.IntegerField(
                default=500, verbose_name="Total Soldering points/day"
            ),
        ),
    ]
