# Generated by Django 5.1 on 2024-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0057_alter_solderingbitrecord_bit_life_remaining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="prepared_by",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="Not OK",
                max_length=100,
            ),
        ),
    ]
