# Generated by Django 5.1 on 2024-08-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0058_alter_solderingbitrecord_prepared_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="prepared_by",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                max_length=100,
            ),
        ),
    ]
