# Generated by Django 5.1 on 2024-08-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0059_alter_solderingbitrecord_prepared_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="checked_by_Operator",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                default="",
                max_length=100,
            ),
        ),
    ]
