# Generated by Django 5.1 on 2024-08-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0060_alter_monthlychecklistitem_checked_by_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="doc_number",
            field=models.CharField(blank=True, default="QSF-13-06", max_length=20),
        ),
    ]
