# Generated by Django 5.1 on 2024-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0062_alter_weeklychecklistitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecklistitem",
            name="machine_location",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="monthlychecklistitem",
            name="machine_location",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="weeklychecklistitem",
            name="machine_location",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=100,
            ),
        ),
    ]
