# Generated by Django 5.1 on 2024-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0064_alter_dailychecklistitem_machine_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="fixture_control_no",
            field=models.CharField(
                choices=[
                    ("51-00-4283-3", "51-00-4283-3"),
                    ("51-00-2603-3", "51-00-2603-3"),
                    ("51-00-1466-3", "51-00-1466-3"),
                    ("57-00-2141-3", "57-00-2141-3"),
                    ("57-00-1891-3", "57-00-1891-3"),
                    ("56-00-1702-3", "56-00-1702-3"),
                    ("56-00-2461-2", "56-00-2461-2"),
                    ("56-00-1019-2", "56-00-1019-2"),
                    ("56-00-1454-2", "56-00-1454-2"),
                    ("56-00-1737-3", "56-00-1737-3"),
                    ("56-00-2305-3", "56-00-2305-3"),
                    ("51-00-2305-3", "51-00-2305-3"),
                    ("51-00-3585-3", "51-00-3585-3"),
                    ("51-00-2629-3", "51-00-2629-3"),
                    ("57-00-1578-3", "57-00-1578-3"),
                    ("57-00-1579-3", "57-00-1579-3"),
                    ("51-00-3228-3", "51-00-3228-3"),
                    ("56-00-2450-3", "56-00-2450-3"),
                    ("52-00-1035-1", "52-00-1035-1"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="fixture_location",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="part_name",
            field=models.CharField(
                choices=[
                    ("tsc_01", "TSC 01"),
                    ("tsc_02", "TSC 02"),
                    ("tsc_04", "TSC 04"),
                    ("tsc_05", "TSC 05"),
                    ("tsc_09", "TSC 09"),
                    ("ebe_01", "EBE 01"),
                    ("csl_01", "CSL 01"),
                    ("dtr_03", "DTR 03"),
                    ("dtr_05", "DTR 05"),
                ],
                max_length=100,
            ),
        ),
    ]
