# Generated by Django 5.1 on 2024-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0066_alter_solderingbitrecord_machine_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="no_dust_on_fixture",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="no_epoxy_coating_on_fixture",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="verification_tag_available",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="verification_tag_condition",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                max_length=25,
            ),
        ),
    ]
