# Generated by Django 5.1 on 2024-08-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0068_startupchecksheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="checkpoint_26",
        ),
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="checkpoint_27",
        ),
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="checkpoint_28",
        ),
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="checkpoint_29",
        ),
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="checkpoint_30",
        ),
    ]
