# Generated by Django 5.1 on 2024-08-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0071_alter_monthlychecklistitem_check_point_12_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visual_defect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dry Solder", "Dry Solder"),
                            ("No Solder", "No Solder"),
                            ("Shorting/ Bridging", "Shorting/ Bridging"),
                            ("Pad Damage", "Pad Damage"),
                            ("Component Tombstone", "Component Tombstone"),
                            ("Solder Ball", "Solder Ball"),
                            ("Green Masking improper", "Green Masking improper"),
                            ("Masking Improper", "Masking Improper"),
                            ("Component Shifted", "Component Shifted"),
                            ("Pad Lifted", "Pad Lifted"),
                            ("Component Damage/Break", "Component Damage/Break"),
                            ("Solder Projection", "Solder Projection"),
                            ("Track Cut (Open)", "Track Cut (Open)"),
                            ("Wrong Polarity", "Wrong Polarity"),
                            ("PTH Shorting", "PTH Shorting"),
                            ("Component Wrong", "Component Wrong"),
                            ("Component Missing", "Component Missing"),
                            ("Solder Dust", "Solder Dust"),
                            ("Pin Hole", "Pin Hole"),
                            ("Component Up Side Down", "Component Up Side Down"),
                            ("LED Defects", "LED Defects"),
                            (
                                "Microcontroller Pin Bend/Damage",
                                "Microcontroller Pin Bend/Damage",
                            ),
                            ("Solder Crack", "Solder Crack"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=100,
                    ),
                ),
                (
                    "programming_defect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Programme does not accept", "Programme does not accept"),
                            ("Pin Voltage low", "Pin Voltage low"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=100,
                    ),
                ),
                (
                    "automatic_testing_defect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Testing fail", "Testing fail"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rejectionsheet",
            name="defects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="screen_app.defects",
            ),
        ),
    ]
