# Generated by Django 5.1 on 2024-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0074_alter_rejectionsheet_defects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rejectionsheet",
            name="part_description",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionsheet",
            name="stage",
            field=models.CharField(
                choices=[
                    ("tsc_01", "TSC 01"),
                    ("tsc_02", "TSC 02"),
                    ("tsc_04", "TSC 04"),
                    ("tsc_05", "TSC 05"),
                    ("tsc_09", "TSC 09"),
                    ("ebe_01", "EBE 01"),
                    ("csl_01", "CSL 01"),
                    ("dtr_03", "DTR 03"),
                    ("dtr_05", "DTR 05"),
                ],
                max_length=200,
            ),
        ),
    ]
