# Generated by Django 5.1 on 2024-08-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0079_alter_startupchecksheet_process_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupchecksheet",
            name="process_operation",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=300,
                verbose_name="PROCESS/OPERATION",
            ),
        ),
    ]
