# Generated by Django 5.1 on 2024-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0082_alter_startupchecksheet_process_operation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="min_skill_required",
        ),
    ]
