# Generated by Django 5.1 on 2024-08-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0083_remove_startupchecksheet_min_skill_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="machine_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="screen_app.machinelocation",
                verbose_name="Process/Operation",
            ),
        ),
    ]
