# Generated by Django 5.1 on 2024-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0084_alter_solderingbitrecord_machine_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="machine_no",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=150,
            ),
        ),
    ]
