# Generated by Django 5.1 on 2024-08-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0093_alter_startupchecksheet_operator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="operator_name",
        ),
        migrations.RemoveField(
            model_name="startupchecksheet",
            name="verified_by",
        ),
    ]
