# Generated by Django 5.1 on 2024-09-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0096_alter_solderingbitrecord_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="approved_by",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="solderingbitrecord",
            name="prepared_by",
            field=models.CharField(
                blank=True,
                choices=[("✔", "OK"), ("✘", "Not OK"), ("", "Not Checked")],
                max_length=100,
            ),
        ),
    ]
