# Generated by Django 5.1 on 2024-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0098_alter_solderingbitrecord_machine_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="PChartData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("part_number_and_name", models.CharField(max_length=200)),
                ("operation_number_and_stage_name", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("month", models.DateField()),
                ("date_control_limits_calculated", models.DateField()),
                ("average_sample_size", models.IntegerField()),
                ("frequency", models.IntegerField()),
                ("sample_size", models.IntegerField()),
                ("nonconforming_units", models.IntegerField()),
                ("proportion", models.FloatField(default=0.0)),
            ],
        ),
    ]
