# Generated by Django 5.1 on 2024-09-09 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0099_pchartdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pchartdata",
            name="date_control_limits_calculated",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pchartdata",
            name="location",
            field=models.CharField(
                choices=[
                    ("visual_inspection", "Visual Inspection"),
                    ("programming_testing", "Programming & Testing"),
                    ("function_testing", "Function Testing"),
                    ("adhesive_application", "Adhesive Application"),
                    ("conformal_coating", "Conformal Coating"),
                    ("housing", "Housing"),
                    ("e90fl", "E90FL"),
                    ("dr_beck_epoxy", "Dr. Beck Epoxy"),
                    ("final_testing", "Final Testing"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="pchartdata",
            name="month",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pchartdata",
            name="operation_number_and_stage_name",
            field=models.CharField(
                choices=[
                    ("DSL01_S01", "DSL01_S01"),
                    ("DSL01_S02", "DSL01_S02"),
                    ("DSL01_S03", "DSL01_S03"),
                    ("DSL01_S04", "DSL01_S04"),
                    ("DSL01_S05", "DSL01_S05"),
                    ("DSL01_S06", "DSL01_S06"),
                    ("DSL01_S07", "DSL01_S07"),
                    ("DSL01_S08", "DSL01_S08"),
                    ("DSL01_S09", "DSL01_S09"),
                ],
                max_length=200,
            ),
        ),
    ]
