# Generated by Django 5.1.5 on 2025-01-17 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0100_alter_pchartdata_date_control_limits_calculated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlchartreading",
            name="lsl",
            field=models.FloatField(
                default=355, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="controlchartreading",
            name="usl",
            field=models.FloatField(
                default=375, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="controlchartstatistics",
            name="lsl",
            field=models.FloatField(default=355),
        ),
        migrations.AddField(
            model_name="controlchartstatistics",
            name="usl",
            field=models.FloatField(default=375),
        ),
    ]
