# Generated by Django 5.1.5 on 2025-01-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0103_historicalcontrolchartreading_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychecklistitem",
            options={
                "verbose_name": "Maintenance Checklist For Daily",
                "verbose_name_plural": "Maintenance Checklists For Daily",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailychecklistitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Maintenance Checklist For Daily",
                "verbose_name_plural": "historical Maintenance Checklists For Daily",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonthlychecklistitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Maintenance Checklist For Monthly",
                "verbose_name_plural": "historical Maintenance Checklists For Monthly",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalweeklychecklistitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Maintenance Checklist For Weekly",
                "verbose_name_plural": "historical Maintenance Checklists For Weekly",
            },
        ),
        migrations.AlterModelOptions(
            name="monthlychecklistitem",
            options={
                "verbose_name": "Maintenance Checklist For Monthly",
                "verbose_name_plural": "Maintenance Checklists For Monthly",
            },
        ),
        migrations.AlterModelOptions(
            name="weeklychecklistitem",
            options={
                "verbose_name": "Maintenance Checklist For Weekly",
                "verbose_name_plural": "Maintenance Checklists For Weekly",
            },
        ),
    ]
