# Generated by Django 5.1.5 on 2025-01-21 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0104_alter_dailychecklistitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="fixture_installation_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="month_year",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalfixturecleaningrecord",
            name="fixture_installation_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalfixturecleaningrecord",
            name="month_year",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
