# Generated by Django 5.1.5 on 2025-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0105_alter_fixturecleaningrecord_fixture_installation_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixturecleaningrecord",
            name="verification_tag_condition",
            field=models.CharField(
                choices=[
                    ("No Peel off", "NO PEEL OFF"),
                    ("No Damage", "NO DAMAGE"),
                    ("Not Available", "Not Available"),
                ],
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfixturecleaningrecord",
            name="verification_tag_condition",
            field=models.CharField(
                choices=[
                    ("No Peel off", "NO PEEL OFF"),
                    ("No Damage", "NO DAMAGE"),
                    ("Not Available", "Not Available"),
                ],
                max_length=250,
            ),
        ),
    ]
