# Generated by Django 5.1.5 on 2025-01-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refresher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_duration",
                    models.IntegerField(
                        blank=True,
                        default=3,
                        help_text="Duration in seconds (for updating the page )",
                    ),
                ),
            ],
        ),
    ]
