# Generated by Django 5.1.5 on 2025-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_app", "0002_refresher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refresher",
            name="time_duration",
            field=models.IntegerField(
                blank=True,
                default=3,
                help_text="Duration in minutes (for updating the page )",
            ),
        ),
    ]
