# Generated by Django 5.1 on 2024-09-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machineapp.machine",
                    ),
                ),
            ],
        ),
    ]
