# Generated by Django 5.1.5 on 2025-01-19 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0002_activemachine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="machines", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
