# Generated by Django 5.1.5 on 2025-01-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0003_machine_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="is_active",
        ),
        migrations.CreateModel(
            name="MachineSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machineapp.machine",
                    ),
                ),
            ],
            options={
                "unique_together": {("machine", "session_key")},
            },
        ),
        migrations.DeleteModel(
            name="ActiveMachine",
        ),
    ]
