# Generated by Django 5.1.5 on 2025-01-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0004_remove_machine_is_active_machinesession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinesession",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="machineapp.machine",
            ),
        ),
    ]
