# Generated by Django 5.1.5 on 2025-01-19 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0006_machineloginstatus_delete_machinesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineLoginTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser_key", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machineapp.machine",
                    ),
                ),
            ],
            options={
                "unique_together": {("machine", "browser_key")},
            },
        ),
    ]
