# Generated by Django 5.1.7 on 2025-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machineapp", "0009_alter_machinelogintracker_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="show_pcb_panel_inspection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="show_rework_analysis",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="show_solder_paste_control",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="show_tip_voltage_resistance",
            field=models.BooleanField(default=True),
        ),
    ]
