# Generated by Django 5.1 on 2024-08-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
